### ISSUE TITLE
Need help adding a class if data field contains specified value.

### ISSUE THREAD

**Issue by jcphlux** [rstaib/jquery-bootgrid#100]
I have been trying to get this function working for most of the day.

    .on("appended.rs.jquery.bootgrid", function (e, array) {
        var isArchivedIndex = $($(grid).find("th[data-column-id='IsArchived']")[0]).index();
        //this gives me a value of 6
        $($(this).find('tbody tr')).each(function (index) {
            if ($.trim($(this).find("td:eq(" + isArchivedIndex + ")").text()) == "Yes") {
            //add the css to the row here.
            }
        });
    })

If I look at the table in the DOM only has the loading row.
Console:    $($(this).find('tbody tr'));
<tr><td colspan="9" class="loading">Loading...</td></tr>

But if I look that the array it shows data
Console:    array
 Response:[Object, Object, Object, Object, Object]

**Comment by rstaib** [comment]
Please provide a [jsfiddle](http://jsfiddle.net) so it is easier for me to help you and to fix your problem together there.
