### ISSUE TITLE
Strange behavior in IE

### ISSUE THREAD

**Issue by shadeven** [rstaib/jquery-bootgrid#103]
Hi,

I switched to IE 11 and encountered strange behaviors during testing. 
1. The icon for search bar disappears, although search function still works.
2. Page number shows as "NaN" when click page numbers in the pagination.

The above issues only happen in IE, FireFox and Chrome are working fine. Please advise. 

Screenshot attached.
![bootgrid_ie_issue](https://cloud.githubusercontent.com/assets/4528306/6206091/d17af9d8-b5d1-11e4-8181-59c90898399d.PNG)

**Comment by shadeven** [comment]
The problem will occur when running in IE version below 8. Just make sure to select Edge in Developer tools.

**Comment by shicks3** [comment]
Thank you for bootgrid.  Works except for the arrows of the pagination controls.  I'm using ajax with a row count of 200, 10 at a time.   I see current, rowcount, etc all work when I click on page buttons 1,2,3,4,5, etc.  But if I click on the right arrow, all the buttons turn to NaN and the POST has NaN for count.
Happens with IE10 and Chrome Version 41.0.2272.89 m.   Using jQuery 1.11.2.   Bootgrid 1.1.4. 

Thank you for any suggestion and help to figure out how to fix.  I'll try to jfiddle but data is on internal network.
