### ISSUE TITLE
Default sort behavior

### ISSUE THREAD

**Issue by BoboITCov** [rstaib/jquery-bootgrid#104]
Hi rstaib,
basically I want to be able to control which column should be used for sorting by default.
I've tried using http://www.jquery-bootgrid.com/Documentation#methods > sort, but don't seem to be able to make it work?
Any hint will be appreciated?

Cheers!

**Comment by shadeven** [comment]
@BoboITCov, 
By default, each column is sortable. You can make it unsortable by adding data-sortable="false" in the table header. Please see below:

<th data-column-id="link" data-formatter="link" data-sortable="false">Link</th>

**Comment by BoboITCov** [comment]
Hi Shadevan,
thank you for the quick reply, but that is not the question here... :)
The way I use the plug-in is: 
  1. generate the data from DB to HTML. There are about 400 records, nothing special.
  1.1. the records are sorted by column 2 (creation date) DESC
  2. init bootgrid (the basic usage example with on "loaded" method extras: commands, etc.)
  2.1. now the records are sorted by column 1 (name) and I have to 
  2.2. click on column 2 until they are again sorted by creation date DESC
So the question is: 
   Is there a way to force the data to be sorted by column N asc/desc on bootgrid init
OR
  Is there a way to force the data to be sorted by column N asc/desc with on "loaded" method?

**Comment by shadeven** [comment]
@BoboITCov,

I guess the "sort" Method could be the way to go although I haven't tried it myself.
On "loaded" event, you can invoke the "sort" method by $("#grid").bootgrid("sort", PlainObject);
You need to define the PlainObject as a dictionary where you can choose the column to be sorted in ascending or descending order. 

Unfortunately the website does not provide such example. Good luck!

**Comment by shadeven** [comment]
@BoboITCov, 
I just discovered that we can sort data by column on init. Simply add "data-order" in the table header. The default value is "", you can set it to "asc" or "desc".

Please see the code snippet below:
<th data-column-id="id" data-identifier="true" data-type="numeric"
data-css-class="custom-column" data-align="right" data-order="asc">ID</th>

**Comment by rstaib** [comment]
@shadeven Thanks for answering the question! 

@BoboITCov [Here](http://www.jquery-bootgrid.com/Documentation#column) you find all existing column settings which will have an impact on initialization.

**Comment by ShemoMFR** [comment]
Hi ! I got a problem with sorting column of bootgrid : I cant sort any column of my table. I tried data-order, data-sortable, etc... its not working. I have other table built with bootgrid and they are working fine. 

Other strange behavior : the first time I am loading the table, I can sort once and after its not working.

If someone has an idea... 

thank you
