### ISSUE TITLE
Adjusting search input field to perform search not on every key

### ISSUE THREAD

**Issue by bestmacfly** [rstaib/jquery-bootgrid#109]
I'm testing jquery-bootgrid and it works quite fine for me. But it seems there is no option for configuring the search box in more detail (ajax-search).
I would like to adjust the search that it only performs a search after at least 4 characters were entered or if return is pressed.
Is there a possibility for realizing this?

Thanks a lot!

Bestmacfly

**Comment by rstaib** [comment]
Done! Version 1.2.0 will be publicly available within the next few days. I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.

**Comment by bestmacfly** [comment]
Thank you a lot, for me the release candidat works fine for issue #109. 
Maybe it would be a good idea to also enable the enter key for searching, but at the moment for me return is absolutely fine.

Best regards

Mark

**Comment by rstaib** [comment]
Enter key to force to search should work (see [commit](https://github.com/rstaib/jquery-bootgrid/commit/e4691fc780f5a6970652240a41ff9670c70ef0f1)). If it is not working as expected, do not hesitate to get back to me.

**Comment by bestmacfly** [comment]
You are right, enter is working also! 

Mark Mescher

Send from my mobile. Please excuse the brevity.

Am 21.04.2015 um 15:39 schrieb Rafael Staib <notifications@github.com <mailto:notifications@github.com> >:

Enter key to force to search should work (see commit). If it is not working as expected, do not hesitate to get back to me.
