### ISSUE TITLE
How to create invisible column that can be read using click event of row

### ISSUE THREAD

**Issue by tonytsunds** [rstaib/jquery-bootgrid#110]
I want a situation where columns can be created and hide at the same time,i should able to read the cell of the row from this column?

**Comment by caverna** [comment]
As a workaround I don't set the data-visible variable as false.
I do use COL tag to set style as "width: 0", ex:
```
<table id="myTable">
    <colgroup>
        <col style="width: 0"/>
        <col />
    </colgroup>
    <thead>...</thead>
    ...
</table>
```

**Comment by rstaib** [comment]
There are two ways to handle that. The first solution is simply set the `data-visible` attribute to the header column. The second solution is simply remove the corresponding HTML header column. The advantage of the second solution is that nothing will be rendered, but rather that some extra information can be provided during rendering or event handling.

**Comment by designseo** [comment]
If we put <code>visible</code> it is also showing at filter tab (image below). How can we hide that one? Sample code would be helpful.
![page editor settingsnew](https://cloud.githubusercontent.com/assets/11888641/7090253/6054e1a2-dfbf-11e4-9170-b207e291a386.png)

**Comment by caverna** [comment]
@designseo  +1 !

**Comment by dcane** [comment]
@designseo can you please tell how you changed the apperance of the grid it look's amazing

**Comment by rstaib** [comment]
@designseo Are you working with the `in-memory` or `server-side` (means requesting data from a service) technique?

**Comment by sommerset** [comment]
I have the same problem:

<thead>
						<tr>
							<th data-column-id="id" data-type="numeric" data-formatter="link_zoom"  >ID</th>
							<th data-column-id="user" data-formatter="link"  data-link="something" >User</th>
							<th data-column-id="user-href" data-visible="false" >href</th>

							<th data-column-id="items" >Items</th>
							<th data-column-id="status" data-converter="status">Status</th>
							<th data-column-id="date" data-order="desc">Date</th>
							<th data-column-id="earnings" data-type="numeric">Earnings ($)</th>
						</tr>
					</thead>
is my table header and I do get the user-href visible on the column selection dropdown.

**Comment by rstaib** [comment]
Today I will release a new version that includes only that feature. Because this issue is duplicated I will refer it to [62](https://github.com/rstaib/jquery-bootgrid/issues/62)!

**Comment by goldyonwar** [comment]
![image](https://cloud.githubusercontent.com/assets/6779821/23448294/0b467292-fe8b-11e6-8dab-9c758372fa4d.png)
![image](https://cloud.githubusercontent.com/assets/6779821/23448313/22b0b0d2-fe8b-11e6-814f-ffab817896c1.png)

**Comment by bellwood** [comment]
Re-opening as this solution doesn't appear to actually address the OP's question:

How can we hide a column from the table but permit its' value to be used when we click a row.

The proposed solution seems to simply allow/deny visibility of the column from the drop down selection.

I have a column, notes, that I do not want to make visible in the table, however, I want it available to command button clicks so I can open a modal to show the notes.

I don't see this being achieved with the release reference in #62 

Thank you =)
