### ISSUE TITLE
Search not work.

### ISSUE THREAD

**Issue by ShiruJan** [rstaib/jquery-bootgrid#112]
When looking at the grid displays the following error: JavaScript runtime error: Object does not support property or method 'search'.

To which may be due this error?

Tnks! =D

**Comment by ShiruJan** [comment]
im using:
$.ajax({
                url: "MyPage.aspx/getDataList"   <--- collection of objects
                , dataType: "json"
                , data: "{}"
                , contentType: "application/json"
                , async: true
                , type: "post"
                , success: function (result) {
                    $("#grid-pos").bootgrid("append", result.d);
                }
            });

**Comment by rstaib** [comment]
I'm not quite sure whether I understand your question right, but if you are trying to search programmatically then use the `search` method instead of writing your own code.

```javascript
$("#grid").bootgrid("search", "your search phrase goes here");
```

**Comment by ShiruJan** [comment]
thank you very much, and sorry for my bad english =P, help :( 
![error](https://cloud.githubusercontent.com/assets/11635458/6832501/9fb42554-d2ec-11e4-96c5-6e7c0aeeb2c5.jpg)

**Comment by rstaib** [comment]
Okay, please provide me a [jsfidlle](http://jsfiddle.net) so I can see what is wrong.

**Comment by ShiruJan** [comment]
I found the problem, I do not put the type of data in each column header. Sorry I'm a potato. =D.
