### ISSUE TITLE
Access the search, sort, page number and row count values via jquery

### ISSUE THREAD

**Issue by laf** [rstaib/jquery-bootgrid#116]
Hi,

Thanks for the amazing library btw :)

Is it possible to get the search, sort, page number and row count values using jquery so that those values can be used to generate links to other pages.

As an example:

http://jsfiddle.net/ywex21m3/1/

You can see here that I'm using a work around to get the search string back from the input box and then also the page numbers from the html code. It would be easier if these can just be referenced directly but I've not found a way to do this.

Thanks

**Comment by rstaib** [comment]
Implemented in version 1.2.0 which will be publicly awailable within the next few days.

**Comment by laf** [comment]
Thank you very much :)

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.

**Comment by laf** [comment]
Hi @rstaib.

Thank you so much for working on this. Just tested and this works perfectly in my environment :)
