### ISSUE TITLE
Search and Pagination not working.

### ISSUE THREAD

**Issue by yellowflash6** [rstaib/jquery-bootgrid#117]
Hi Rafael!
I have used Command Buttons type Grid for my purpose. I am using AJAX with Bootgrid to load the data as explained. It is working fine. Data is being populated.

What I am facing is
1. Search functionality is not working.
2. Pagination is not working. All records are shown.

I have set rowCount and total correctly. But Pagination is not happening.

I have tried the same using some static data and it is working fine - Search and Pagination.

Thanks.

**Comment by laf** [comment]
Are you returning current, rowCount and total in your json response?

**Comment by yellowflash6** [comment]
Laf,

Yes. I am returning the rowCount and current correctly.

I have fixed the problem. With static data, the grid will paginate the data accordingly. Whereas with dynamic data, we have to feed the correct data according to the pagination. That is, if we click page number 2 where rowCount is say 10, it will send a POST request to our API with these parameters. And, we have to send the data set accordingly; second set of records when the record count is 10.

Thanks

**Comment by dmbuso** [comment]
I'm having the same problem. My controller method action is this:
        public ActionResult _JournalList()
        {
            var json = "";
            if (Request.IsAjaxRequest())
            {
                var keyValues = new Dictionary<string, object>
               {
                   { "rows", _db.Journals.OrderByDescending(x=>x.JournalDateTime).ToList()},
                   { "rowCount", _db.Journals.ToList().Count() },
                   { "total", _db.Journals.ToList().Count() },
                   { "current", Request.Params.GetValues("current")}
               };
                JavaScriptSerializer js = new JavaScriptSerializer();
                json = js.Serialize(keyValues);
                return Json(json, JsonRequestBehavior.AllowGet);
            }
            return Json(json, JsonRequestBehavior.AllowGet);
        }
