### ISSUE TITLE
Noticeable flicker on any table update

### ISSUE THREAD

**Issue by ilyai** [rstaib/jquery-bootgrid#118]
I guess this is not intentional. Can anything be done in order to negate this issue?

**Comment by rstaib** [comment]
Not yet, but consider an improvement in version 1.2.0.

**Comment by rstaib** [comment]
I fixed it partially by configuring a delay of 250 milliseconds. In case the service responds in less than 250 milliseconds the loading mask will not show up. Please open an new issue whether the flicker still occurs and bothers you. Version 1.2.0 will be publicly available in the next few days.

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.

**Comment by ilyai** [comment]
Thanks a lot for your work, but I'm currently using [Bootstrap Table](http://bootstrap-table.wenzhixin.net.cn/) in my project. Maybe next time I'll try out this component.

**Comment by rstaib** [comment]
Okay thanks anyway!
