### ISSUE TITLE
How to update Row Data and Reload Grid

### ISSUE THREAD

**Issue by nishantagg** [rstaib/jquery-bootgrid#119]
Hi All,
I am trying to update the grid data when user click's on a link column. Depending upon the result of clicked link i am not able to persistently update the table. Please help.

Thanks,
Nishant Aggarwal

**Comment by rstaib** [comment]
You need to call the `reload` method described [here](http://www.jquery-bootgrid.com/Documentation#methods).

```javascript
$("#grid").bootgrid("reload");
```

Please close this issue whether your question is answered - thanks!

**Comment by nishantagg** [comment]
Thanks Rafael for your reply. But for some reason when i called the reload method column was not accepting the new value. Grid refreshes the column to older value. Anyways i got rid of this with a work-around.

Thanks,
Nishant Aggarwal

**Comment by marlonpya** [comment]
Yes i too, we have this prblem S:
