### ISSUE TITLE
jquery-bootgrid is not a valid tag on StackOverflow

### ISSUE THREAD

**Issue by eappell** [rstaib/jquery-bootgrid#12]
Just wanted to point out that you are requesting people ask questions on StackOverflow and tag their requests with jquery-bootgrid, but that isn't yet a tag on S.O..  It requires a reputation of 1500 or higher to create a new tag, and I'm not even close to that, so I couldn't create the tag, but I do need to ask a question.  I ended up prefixing my question with 'jquery-bootgrid'.  I hope you can find it.  Please create the tag, and then everyone can use it to post questions.  Thanks!

**Comment by thiagosb13** [comment]
I think this issue could be closed because jquery-bootgrid is already a tag on StackOverflow.

**Comment by eappell** [comment]
Agreed, thanks for pointing that out!  It took a couple years, but glad it got done.
