### ISSUE TITLE
bootgrid doesn't work when navigation property has 1 or 2

### ISSUE THREAD

**Issue by lvv83** [rstaib/jquery-bootgrid#120]
Hello.
This issue already mentioned here (#81), but closed without any fix.

if we set **navigation** property to **1** or **2** then error raised because **this.header** (or **this.footer**) is null.

I replace this (and similar) lines:
``` javascript
headerActions =  this.header.find(selector),
footerActions = this.footer.find(selector);
```
with
``` javascript
headerActions = this.header ? this.header.find(selector) : [],
footerActions = this.footer ? this.footer.find(selector) : [];
```
and its work!

**Comment by rstaib** [comment]
I have fixed it already [here](https://github.com/rstaib/jquery-bootgrid/tree/fixes-and-features) but I have some more points on my checklist before releasing the next version. Thanks anyway and of course for creating the ticket for transparency.

**Comment by rstaib** [comment]
Fixed in version 1.2.0 which will be publicly available within the next few days.

**Comment by lvv83** [comment]
Thanks!

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.

**Comment by lvv83** [comment]
Well, I already use bootgrid from fixes-and-features branch. It's works properly with navigation.
Prerelease version from Nuget without navigation bugs too.

I have some questions, which not related to this issue. I'm novice with your great component, so I need for some time to learn examples and research.

Thank you.
