### ISSUE TITLE
Testing jQuery-Bootgrid with JSFiddler

### ISSUE THREAD

**Issue by ravick4u** [rstaib/jquery-bootgrid#123]
Hey,

I am new to this and this might look like a silly quetion to you.

I am trying to test basic example with jsfiddler and its not working

below is the link for jsfiddler.

http://jsfiddle.net/zms3draq/3/

**Comment by rstaib** [comment]
http://jsfiddle.net/zms3draq/4/

**Comment by ravick4u** [comment]
thanks
