### ISSUE TITLE
Decimal Separator

### ISSUE THREAD

**Issue by jailsoncarneiro** [rstaib/jquery-bootgrid#137]
How to define a display format for a numeric column?
I need to show values like 23.99 as 23,99 (comma instead of point) maintaining this column's sort condition.
Thanks!

**Comment by rstaib** [comment]
Short answer is use `converters` (see [here](http://www.jquery-bootgrid.com/Documentation#converters) for documentation).

[Here](http://jsfiddle.net/hdhfxLoa/) you find a dummy implementation.

**Comment by jailsoncarneiro** [comment]
Thank you, the second link had (fiddle) really helped. ;-)
