### ISSUE TITLE
Preserve links

### ISSUE THREAD

**Issue by rasmustaarnby** [rstaib/jquery-bootgrid#15]
Is there a way to preserve links in the table cells?

**Comment by mordyovits** [comment]
+1 :-/

**Comment by LuanP** [comment]
+1

Since the links weren't appearing in the table cell, I tried adding the links to the <tr> tag and I get it's attributes through a formatter, but I couldn't figure it out how.

I needed something like:

```html
<table>
  <thead>
    <tr>
      <th data-column-id="commands" data-formatters="commands">Comandos</th>
    </tr>
  </thead>
  <tbody>
    <tr data-update-url="/update/1/" data-delete-url="/delete/1/">
      <td></td>
    </tr>
  </tbody>
</table>
```

--------

```javascript
$('#table').bootgrid({
  formatters: {
    "commands": function (column, row) {
      return "<a href='" + $(some_magic_way_of_getting_tr_element_here).data('update-url') + "'>Editar</a><a href='...'>Remover</a>"
    }
  }
});
```

Is that possible?

**Comment by siamkreative** [comment]
+1
I would also love to be able to preserve links without having to create formatters for each or edit the source code.

**Comment by joannarom** [comment]
Not sure how well this works yet, but I ran into the same issue as mentioned above. I am transitioning my pages from using datatables to bootgrid, and did not want to use the formatter options for my hrefs. I took a look at the source code and was able to change the loadRows function line:285 from.text() to .html() and the contents rendered as it should. 

original:  row[column.id] = column.converter.from(cells.eq(i).text());
new:  row[column.id] = column.converter.from(cells.eq(i).html());

**Comment by alin3661** [comment]
+1
I would also love to be able to preserve links. Would we be seeing this feature in the next release?

**Comment by paratoner** [comment]
I added new data-... attribute that named `isitemtemplate` and changed the code like this : 

```
$.each(that.columns, function (i, column) {
    if(column.isitemtemplate){ 
        row[column.id] = column.converter.from(cells.eq(i).html());
    } else {
        row[column.id] = column.converter.from(cells.eq(i).text());
    }
});
```

**Comment by bkilshaw** [comment]
Any chance of adding this in? Seems like odd functionality to alter the content of the cell in such a drastic manner?

**Comment by larini** [comment]
+1
I hate to write formatters.

**Comment by rodrigomocca** [comment]
If this cannot be done I'll have to change bootgrid for another, this is not even planned?

**Comment by VeNoMouS** [comment]
For my 2 cents...
add data-formater on your head colomn

```
<th data-column-id="show" data-formatter="link">Show</th>
```

Then in the table element

```
<td><a href="#">{"url":"<url_goes_here>","text":"<text_to_display>"}</a></td>
```

add formarter in the bootgrid

```
$(document).ready(function(){
    $("#data-table-basic").bootgrid({
        formatters: {
            "link": function(column, row) {
                var json_data = JSON.parse(row.show);
                return "<a href=\"" + json_data.url + "\">" + json_data.text + "</a>";
            }
        }
    });         
});
```

**Comment by poveron** [comment]
Great joannarom, your suggestion was fantatisc, works for me!!

**Comment by BusterNeece** [comment]
+1 to this, it seems that it's been nearly a year that this request has been in the pipeline and there isn't much additional information about it...it's a bit disheartening that I have to manually edit a common library just to keep it from messing up my existing table HTML so severely.

**Comment by Mohammed-Daud** [comment]
```
<thead>
    <tr>
        <th data-column-id="doc" data-formatter="doc" data-column-id="doc">Document</th>
    </tr>
</thead>
```
```
<tbody>
<tr>
<td>

<?php echo $someName; ?>###<?php echo $someUrl; ?>

</td>
</tr>
</tbody>
```

```
<script type="text/javascript">
  $("#grid-basic").bootgrid({
    formatters: {
      "doc": function (column, row){
        for (var doc in row) {
            if (row.hasOwnProperty(doc)) {
                var str = row.doc.split("###");
                return "<a href=\" "+ str[1] +" \">" + str[0] + "</a>";
            }
        }
      }
    }
  });
</script>
```
