### ISSUE TITLE
How Can I use the Bootstrap Modal in bootgrid Command button

### ISSUE THREAD

**Issue by jeysinghanbu** [rstaib/jquery-bootgrid#157]
I am trying open bootstrap modal in command edit and delete button.
  
 ![command button](https://cloud.githubusercontent.com/assets/4211519/8186684/5f8fc370-1469-11e5-9076-8cccaeb09764.PNG)
         
  It doesn't work
           data-toggle=\"modal\" data-target=\"#confirmation\"

  Here my jQuery Code
            $( document ).ready(function() {
            $("#grid-plant").bootgrid({
            caseSensitive: false,
            columnSelection: false,

            formatters: {
                "commands": function (column, row) {
                    return "<button type=\"button\" class=\"btn btn-xs btn-default command-edit\"  data-toggle=\"modal\" data-target=\"#confirmation\"><span class=\"fa fa-pencil\"></span></button> " +
                        "<button type=\"button\" class=\"btn btn-xs btn-default command-delete\" ><span class=\"fa fa-trash-o\"></span></button>";
                }
            }
        })
        });

**Comment by jeysinghanbu** [comment]
http://stackoverflow.com/questions/29030352/jquery-bootgrid-modal-dialog

**Comment by jeysinghanbu** [comment]
Finally Got :) it is working. 

Opening Bootstrap Modal on Click Event.


             .on("loaded.rs.jquery.bootgrid", function () {
             /* Executes after data is loaded and rendered */
             $(this).find(".command-delete").click(function (e) {
            $($(this).attr("data-target")).modal("show");
        });
    });

Full jQuery Code Here:  
  
            $( document ).ready(function() {
            $("#grid-plant").bootgrid({
            caseSensitive: false,
            columnSelection: false,

            formatters: {
                "commands": function (column, row) {
                    return "<button type=\"button\" class=\"btn btn-xs btn-default command-edit\"  data-toggle=\"modal\" data-target=\"#confirmation\"><span class=\"fa fa-pencil\"></span></button> " +
                        "<button type=\"button\" class=\"btn btn-xs btn-default command-delete\" ><span class=\"fa fa-trash-o\"></span></button>";
                }
            }
        }).on("loaded.rs.jquery.bootgrid", function () {
            /* Executes after data is loaded and rendered */
            $(this).find(".command-delete").click(function (e) {
                $($(this).attr("data-target")).modal("show");
            });
        });
        });

**Comment by Nitrotoxin** [comment]
Can you tell me how you passed the record id to the delete button so you could delete the record?  I have my modal working as per your code above I just need to pass the record id to the modal so I can do the PHP and delete the record from my MySQL database.  Thank you!

**Comment by juanvilu** [comment]
`.on("loaded.rs.jquery.bootgrid", function(){
 grid
.find(".command-edit")
 .on("click", function(e)
  {
        console.log( e.currentTarget );
        $($(e.currentTarget).attr("data-target")).modal("show");
})`

**Comment by Nitrotoxin** [comment]
Thank you I got it working a long time ago but I appreciate your response, I should have posted back the resolution to the issue I was having.  I am now passing multiple values using this and AJAX and its working beautifully.

Thank you

**Comment by zaibtabs** [comment]
Hi Everyone, I am new to this and so far I manage to run a jquery.bootgrid and data is displayed nicely with edit and delete buttons, however I am struggling to open a modal window and on.click of edit the select record.

Please can someone help.
here is my ajax.js script code.  further down is a fetchrecord.php file, which i would like to display in a modal window with save and close button.

 

```
$(document).ready(function(){
 

 var employeeTable = $('#employee_grid').bootgrid({
  ajax: true,
  rowSelect: true,
  post: function()
  {
   return{
    id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
   };
  },
  url: "fetch_data.php",
  formatters: {
   "commands": function(column, row)
   {
		
    return "<button type=\"button\" class=\"btn btn-xs btn-default command-edit\" data-row-id=\"" + row.emp_id + "\"><span class=\"glyphicon glyphicon-edit\"></span></button> " + 
		                "<button type=\"button\" class=\"btn btn-xs btn-default command-delete\" data-row-id=\"" + row.emp_id + "\"><span class=\"glyphicon glyphicon-trash\"></span></button>";
	}
			}
												});

// On load of document, pick row-id and perform crud operations.  
// This is where I am having problems.
												
 $(document).on("loaded.rs.jquery.bootgrid", function () {
   //Remove event handlers
   $(this).find(".command-edit").off();
   $(this).find(".command-delete").off();
   $(this).find(".command-add").off();

   $(this).find(".command-edit").on("click", function (e) {
     alert("You pressed edit on row: " + $(this).data("row-id"));
   }).end().find(".command-delete").on("click", function (e) {
     alert("You pressed delete on row: " + $(this).data("row-id"));
   }).end().find(".command-add").on("click", function (e) {
     /* Yout button logic */
   });
});
}); 
```

My php fetchsinglerecord.php code.

```
<?php
//fetch_single.php

include_once("db_connect.php");

if(isset($_POST["eid"]))
{
 $output = array" ";
 
 $query = "SELECT * FROM employee WHERE id = '".$_POST["eid"]."'";
 $result = mysqli_query($connection, $query);
 while($row = mysqli_fetch_array($result))
 {
  $output["id"] = $row["id"];
  $output["employee_name"] = $row["employee_name"];
  $output["employee_salary"] = $row["employee_salary"];
  $output["employee_age"] = $row["employee_age"];
  
 }
 echo json_encode($output);
}
echo json_encode($output);
?>
```
How do i get this record from fetchsingle.php in a modal window.  Please helpl
