### ISSUE TITLE
How disable pagination

### ISSUE THREAD

**Issue by KaduAmaral** [rstaib/jquery-bootgrid#163]
How disable pagination and load all content in one single page?

**Comment by philwig** [comment]
It's an option called "navigation". Set it to zero to turn off paging. Eg

     $("#RTFM_Grid").bootgrid(
                {
                    navigation:0    // Turn of paging.
                }
            );

**Comment by KaduAmaral** [comment]
Now is showing only 10 lines. How to display all?

**Comment by KaduAmaral** [comment]
It's an option called "rowCount". I put value "-1" and is solved.

```
$("#datagrid").bootgrid({
rowCount: -1
});
```

**Comment by Nitrotoxin** [comment]
Thank you this solved my issue as well! Much appreciated!
