### ISSUE TITLE
documentation - typos

### ISSUE THREAD

**Issue by pashute** [rstaib/jquery-bootgrid#187]
**Converter**
The converter consits of to methods from and to.
*consits -> consists
*of to -> of two
*methods -> methods:
Should be: The converter consists of two methods: from and to

**Templates**
*noticed does -> have noticed
*on rendering -> upon rendering
 *There three -> There are three
*of placeholder -> of placeholders.
*) more or less... are -> ) are more or less...

*Change to the following: 
As you may already have noticed, some templates and labels contain strange content parts like {{ctx.icon}}. These are dynamic placeholders which will be replaced upon rendering. There are three different types of placeholders. ctx is a dynamic context-sensitive container, whereas css (CSS container) and lbl (label container) are more or less static containers (they are linked directly to the  CSS and  label settings).

**Comment by rstaib** [comment]
Thank you for the valuable contribution - very appreciated!
