### ISSUE TITLE
Split long row

### ISSUE THREAD

**Issue by YairHadari** [rstaib/jquery-bootgrid#191]
Hi,
I"m trying to split long row using data-formatter (return "<p class='break-row'>" + row.Detailes + "</p>";) and CSS (p.break-row {
    width: 150px; 
    border: 1px solid #000000;*/
    word-break: break-all;
}) but nothing help.

Can U please asist?
Thanks,
Yair

**Comment by YairHadari** [comment]
I have added data-css-class="break-row" to the column definition, changed the css to 
.break-row {
    	width: 150px;
	word-break: break-all;
    	border:2px solid; 
}
But it's still not working

**Comment by YairHadari** [comment]
The solution is:
In the html file:
<th data-column-id="Detailes" data-css-class="break-row">Detailes</th>

in the CSS:
.break-row {
    	width: 30px;
	word-wrap: break-word;
	text-align: right;
}

.bootgrid-table td {
    white-space: normal; !important
}

**Comment by acorreaf** [comment]
Danke!
