### ISSUE TITLE
Overriding defaults

### ISSUE THREAD

**Issue by philwig** [rstaib/jquery-bootgrid#201]
I think I figured out how to override the defaults without hacking the source code on a global basis. The documentation explains how to do this for each individual case, but I want to do it for all the grids in my site, not one by one. So this works, to tweak both the CSS and the labels used, for example, in some code I load for every page, early in the cycle:

```
$.extend($.fn.bootgrid.Constructor.defaults.css, {
    searchField: "search-field form-control input-sm"
});
$.extend($.fn.bootgrid.Constructor.defaults.labels, {
    noResults: "No rows"
});
```

I'd hoped that I could combine these in one hit, like this:

```
$.extend($.fn.bootgrid.Constructor.defaults, {
    css: {  searchField: "search-field form-control input-sm" },
    labels: {  noResults: "No rows" }
});
```

But that no workie. Does anyone know how to do this in one jQuery call?

**Comment by rstaib** [comment]
You need to tell the `extend` method to do a deep copy. Thats it.

``` javascript
$.extend(true, $.fn.bootgrid.Constructor.defaults, {
    css: {  searchField: "search-field form-control input-sm" },
    labels: {  noResults: "No rows" }
});
```

**Comment by philwig** [comment]
Thanks - that'll be the one!

**Comment by mvcmaker** [comment]
It works! Thanks @rstaib!
