### ISSUE TITLE
Merged table Header cells?

### ISSUE THREAD

**Issue by imman731** [rstaib/jquery-bootgrid#210]
Hi, is it possible to create merged table header cells?
just like html table (rowspan and colspan), as below...
I try to using this code to Bootgrid table ,but is not work.
I'm looking around but I can't find anything related to this.
## Thanks

<table border="1">
<thead>
  <tr>
    <th rowspan="2">State</th>
    <th rowspan="2">Utilities Company</th>
    <th colspan="3">Summer Period</th>
  </tr>
  <tr>
    <th>data1</th>
    <th>data2</th>
    <th>data3</th>
  </tr>
</thead>
<table>

**Comment by rstaib** [comment]
No, but perhaps in the future.
