### ISSUE TITLE
fixed column width

### ISSUE THREAD

**Issue by peters59** [rstaib/jquery-bootgrid#22]
is it possible to set a column width for each column?
Regards
peter

**Comment by jhargis** [comment]
is this in the documentation somewhere? I didn't see it.

**Comment by K232** [comment]
@jhargis , see http://www.jquery-bootgrid.com/Documentation#column. The functions are described correct, but unfortunately the name is not correct in some cases :-( Correct is 'data-header-css-class'.

**Comment by rstaib** [comment]
The *fixed column width* feature is part of version 1.2.0 will be publicly available within the next few days.

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.
