### ISSUE TITLE
Search on formatter column

### ISSUE THREAD

**Issue by patricksamson** [rstaib/jquery-bootgrid#227]
Hi!
Is it possible to search on a column using a formatter.
Currently, searching on a datagrid that contains a search-enabled formatted column throws an error. 
Here it is : 

```
TypeError: b.converter.to(a[b.id]).search is not a function. (In 'b.converter.to(a[b.id]).search(c)', 'b.converter.to(a[b.id]).search' is undefined)
cjquery.bootgrid.min.js:5:2113
wherejquery.bootgrid.min.js:5:23092
njquery.bootgrid.min.js:5:2973
Bjquery.bootgrid.min.js:5:10231
(anonymous function)jquery.bootgrid.min.js:5:10090
```

There a a few ways how this could be achieved : 
1. Consider the column as a string and search it
2. Remove the possible HTML tags from the column and search the remaining text
3. Pass the content of the column to a converter and search the results

I already tried the third option, but it throws the same error.

Thoughts?

**Comment by wangjingling** [comment]
I resolve the same error by add data-type="numeric" to column has an interger data

**Comment by brutaldev** [comment]
There are a number of pull requests that already fix this so not going to add another one. For a quick fix just replace the following code in jquery.bootgrid.js
```
column.converter.to(row[column.id]).search(searchPattern) > -1`
```
with 
```
searchPattern.test(column.converter.to(row[column.id]))
```
