### ISSUE TITLE
Trying bootgrid with Php and MySQl Query with Multiple Joins

### ISSUE THREAD

**Issue by abstractindia** [rstaib/jquery-bootgrid#244]
I am trying to use bootgrid with a sql containing joins. I am able to get the json array output in browser window. But when I set the data-url to that file, i don’t get the tbody rendered. It just displays loading…

For your reference I have posted my code at pastebin. Here it is File with table:  (http://pastebin.com/1eXyeb2e) and here is the query: beneficiaries_json.php (http://pastebin.com/inisjk41), the one referenced in the data-url.

Can you please guide me what’s wrong I am doing?

**Comment by abstractindia** [comment]
The console shows the following error:

```
Cannot read property 'length' of undefined
```

at line 585 in jquery.bootgrid.js file.

And the line 585 in jquery.bootgrid.js is:

```
 if (rows.length > 0)
```

**Comment by nickylau82** [comment]
response json data should like this:
``` javascript
{
  "current": 1,
  "rowCount": 10,
  "rows": [
    {
      "id": 19,
      "sender": "123@test.de",
      "received": "2014-05-30T22:15:00"
    },
    {
      "id": 14,
      "sender": "123@test.de",
      "received": "2014-05-30T20:15:00"
    },
    ...
  ],
  "total": 1123
}
```
so,your query data should be translate to new json string like this
