### ISSUE TITLE
TypeError: rows is undefined

### ISSUE THREAD

**Issue by kim2235** [rstaib/jquery-bootgrid#26]
Hi I was trying the command sample from your website but I ran into an error saying that "rows is undefined     

if (rows.length > 0)" from firebug its on line 565

all I did was this 

   <table id="grid-data" class="table table-condensed table-hover table-striped" >
       <thead>
           <tr>

```
           <th data-column-id="sender" data-order="asc">Fullname</th>
           <th data-column-id="username">Email Address</th>
           <th data-column-id="lvl" >Role</th>
           <th data-column-id="status" >Status</th>
           <th data-column-id="date-reg" >Date Registered</th>
           <th data-column-id="last-log" >Last Login</th>
           <th data-column-id="commands" data-formatter="commands" data-sortable="false">Commands</th>
       </tr>
   </thead>
 </table>
```

<script src="assets/plugins/jquery.bootgrid/jquery.bootgrid.js"></script>

```
<script>$("#grid-data").bootgrid({
 ajax: true,
 post: function ()
        {
        /* To accumulate custom parameter with the request object */
        return {
        id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
        };
        },
    url: "fetchdata.php",
formatters: {
commands: function (column, row)
    {
    /* "this" is mapped to the grid instance */
    return "<i class='fa fa-pencil'></i><button type=\"button\" class=\"btn btn-xs btn-default suspends\" data-row-id='"+row.id+"'><i class='fa fa-warning'></i></button>";
    }
}
}).on("loaded.rs.jquery.bootgrid", function() {
    $("#grid-data").find(".suspends").on("click", function(e)
        {
        alert("You pressed edit on row: " + $(this).data("row-id"));
        });
});</script>
```

the php file looks something like this 

while($r = $user->fetch()) {
    $rows[] = $r;
}
print json_encode($rows);

did I do something wrong here? please help thanks

**Comment by shura25** [comment]
Hi, 
I have the same error. I'am using a webservice and the response is the following:
{"current": 1,"rowCount": 10,"rows": [{"num_identificacion": "111940526","nom_apellido1": "Rodriguez","nom_apellido2": "Guzman","nom_nombre": "Pablo"},{"num_identificacion": "303910137","nom_apellido1": "Solano","nom_apellido2": "Mora","nom_nombre": "Marianella"}], "total": 2}

The javascript code is:

 $('#tblBusqueda').bootgrid({
        ajax: true,
        ajaxSettings: {
            method: "GET",
            cache: false
        },
        searchSettings: {
            delay: 100,
            characters: 3
        },
        labels: {
            noResults: "No hay resultados",
            search: "Buscar",
            loading: "Cargando...",
            all: "Todos",
            infos: "Mostrando {{ctx.start}} a {{ctx.end}} de {{ctx.total}} registros",
            refresh: "Refrescar"
        },
        post: function () {
            /\* To accumulate custom parameter with the request object */
            return {
                id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
            };
        },
        url: "/WebServices/ServicioPensionesASMX.asmx/ConsultarPersonasJSON",
        selection: true,
        multiSelect: true
    });

Thanks for your help.
