### ISSUE TITLE
Send RQ to server as JSON

### ISSUE THREAD

**Issue by seiyapl** [rstaib/jquery-bootgrid#27]
It would be nice to have that feature build-in. Currently when I'm sending JSON as string from requestHandler, the contentType is set to "application/x-www-form-urlencoded", which cannot be interpreted correctly on server-side.

**Comment by rstaib** [comment]
In version 1.2.0 you will be able to override all settings of the `$.ajax()` method except `data`, `error`, `success` and `url`. Version 1.2.0 will be publicly available within the next few days.

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.

**Comment by seiyapl** [comment]
Hi. It looks promising (I've seen the commited code). I will check that as soon as I can. Hopefully today or tomorrow.

**Comment by seiyapl** [comment]
Could you just provide me with bootgrid .js file? I'm not using npm nor nuget and I can't find a way to simply download bootgrid from the web.

**Comment by rstaib** [comment]
Just grab it from [here](https://github.com/rstaib/jquery-bootgrid/tree/fixes-and-features/dist).

**Comment by seiyapl** [comment]
I can confirm that it works.
