### ISSUE TITLE
Excel/CSV Support?

### ISSUE THREAD

**Issue by surgiie** [rstaib/jquery-bootgrid#309]
Is there any way i can get the data from the grid  (full record set or search filtered data) and use it to convert to something like csv or does the grid support excel export?

**Comment by soongsta** [comment]
Were you able to find a solution?

**Comment by surgiie** [comment]
@soongsta I ended up using https://github.com/hhurz/tableExport.jquery.plugin

**Comment by soongsta** [comment]
Cheers @surgiie. Did you get it to work with bootgrid? Or just a plain html table?

**Comment by surgiie** [comment]
@soongsta it exports html tables which is what the grid is so it works either way:)

**Comment by soongsta** [comment]
Cool, I got it to work finally. For anyone who is interested, see here https://jsfiddle.net/soongsta/1ajxbddy/

**Comment by surgiie** [comment]
There is some issues with the file format for your jsfiddle saying its in sylk format and may or may not open all the time.

 @soongsta

**Comment by surgiie** [comment]
What i did using https://github.com/hhurz/tableExport.jquery.plugin (a fork of tableExport)

For my purposes i only needed pdf/csv support but there are other export formats.

at the end of my body

```
<script type="text/javascript">
   function exportPDF() {
     $('#grid-data').tableExport(
     {
        fileName:'report',
         type:'pdf',
         jspdf:
         {orientation: 'l',
             format: 'a3',
             margins:
             {
               left:10, right:10, top:20, bottom:20
             },
             autotable:
             {
                styles:
                {
                    fontSize: 12,
                    fillColor: 'inherit', 
                    textColor: 'inherit'
                },
                tableWidth: 'auto'
            }
        }
     });
  }
  function exportExcel() {
     $('#grid-data').tableExport(
     {
         fileName:'report',
         type:'csv',
         jspdf:
         {orientation: 'l',
             format: 'a3',
             margins:
             {
               left:10, right:10, top:20, bottom:20
             },
             autotable:
             {
                styles:
                {
                    fillColor: 'inherit', 
                    textColor: 'inherit'
                },
                tableWidth: 'auto'
            }
        }
     });
  }
</script>

```

then i had an onclick event button call one of the functions as needed.

There seems to be warnings with excel format but CSV works fine for me:)

**Comment by soongsta** [comment]
Good to know, 
Thanks @surgiie

**Comment by jefferyleo** [comment]
@soongsta it doesn't working if my first column in bootgrid table is data-visible="false"

**Comment by soongsta** [comment]
@jefferyleo I have not used this component for a long time. Try posting a new issue

**Comment by jefferyleo** [comment]
@soongsta alright, however this plugin has been stopped develop by the developer I guess.
