### ISSUE TITLE
x-editable integration possible?

### ISSUE THREAD

**Issue by appel** [rstaib/jquery-bootgrid#35]
Would it be possible to integrate [x-editable](http://vitalets.github.io/x-editable/) (or something similar) in jQuery Bootgrid for inline editing? If so, any jsfiddle links out there?

**Comment by Nerian** [comment]
@appel Did you get this to work?

**Comment by appel** [comment]
Unfortunately, not yet. And then work got in the way... :( If I do get it working in the future I'll post it here.

**Comment by Nerian** [comment]
I got it working like this:

```
$.fn.editable.defaults.mode = 'inline';

$("#gradebook").bootgrid({
  ...   
}).on("loaded.rs.jquery.bootgrid", function (e){
  $('[data-xedit]').each(function(entry){    
    entry.editable({
      type: 'text',
      name: 'score',
      url: "...someurl",      
      title: 'Enter score'
    });
  })
 });
```

**Comment by appel** [comment]
@Nerian wow, that's awesome! Would you mind setting up a jsfiddle by forking [this](http://jsfiddle.net/appel/dec4gqb0/) as a base?

**Comment by agrezev** [comment]
**@Nerian** what is ``` '[data-xedit]' ``` in your code? Name of `<tr>` tag?
If it possible give example of marking

**Comment by daneshqureshi** [comment]
@Nerian Is this working now?

**Comment by Nerian** [comment]
If I remember correctly, it was the name of the span:  

```
<td><span data-xedit='true'>03 Aug 2014</span></td>

$.fn.editable.defaults.mode = 'inline';

$("#gradebook").bootgrid({
  ...   
}).on("loaded.rs.jquery.bootgrid", function (e){
  $('[data-xedit]').each(function(entry){    
    entry.editable({
      type: 'text',
      name: 'score',
      url: "...someurl",      
      title: 'Enter score'
    });
  })
 });
```

**Comment by KamelKaouech** [comment]
@Nerian Can you please post the x-editable bootgrid example in jsfiddle? Many thanks in anticipation

**Comment by vmpande** [comment]
Hey, would anyone be kind enough to post the answer with jsfiddle! Would be really helpful. Thanks!

**Comment by Nerian** [comment]
Sorry, I no longer have the code. It was 3 years ago.

**Comment by Vickthor27** [comment]
1.- Add a class over the HTML

`<th data-column-id="comentario"  data-width="70%"  data-css-class="student_name"> COMENTARIOS </th>`

2.-  Change the class property 'contenteditable' in the onloaded function. 
`.on("loaded.rs.jquery.bootgrid", function()
        {          
        grid.find(".student_name").on("click", function(e){
         $('.student_name').attr("contenteditable", "true");
        });`
