### ISSUE TITLE
Link one grid to another

### ISSUE THREAD

**Issue by bellwood** [rstaib/jquery-bootgrid#357]
I am working on a lite DNS editor... I can very easily get all my zones to load up in the first grid and have my rows setup using the click handler that then gives me an alert with the ID (perfect)

What I need some assistance with is somehow passing that to the second grid.

I've created the HTML and script for the second grid (unique ID, etc), however, I cannot seemingly find a way to pass that ID over to an action that the second grid will then use and reload with the records for the chosen zone.

I didn't see any stackoverflow or other examples show this functionality.

Anyone out there have grids tied together?

**Comment by derrekbertrand** [comment]
http://www.jquery-bootgrid.com/Documentation#events

It appears you can use events and methods, although I have not tried it. I'd see if there is an event you can tie to one grid, and then fire a method on your second grid to update it/load it.

**Comment by stvowi** [comment]
http://gijgo.com/grid/demos/connected-jquery-grids

**Comment by bellwood** [comment]
Thank you @stvowi
