### ISSUE TITLE
Add view button ! 

### ISSUE THREAD

**Issue by BourAbdelhadi** [rstaib/jquery-bootgrid#370]
Fixed

**Comment by bellwood** [comment]
Commands are created within the "commands" formatters.

It looks like you're using part of the demo from here:

https://www.phpflow.com/jquery-plugin-2/jquery-bootgrid-bootstrap-grid-control-plugin/
https://phpflow.com/demo/bootgrid-php-mysql-serverside-demo/

...I suggest reviewing it and adapting as needed to your needs.
