### ISSUE TITLE
pagination with bootstrap 4

### ISSUE THREAD

**Issue by RezaErfani67** [rstaib/jquery-bootgrid#388]
pagination is not looks properly with bootstrap 4

**Comment by canchito-dev** [comment]
Hi,
I ran into the same problem, and this worked for me. Hope it helps you too

```javascript
$.extend($.fn.bootgrid.Constructor.defaults, {
        css: {
            pagination: "pagination",
            paginationButton: "page-link",
        },
	templates: {
            pagination: '<ul class="{{css.pagination}} pagination-sm"></ul>',
            paginationItem: '<li class="page-item"><a class="page-link" data-page="{{ctx.page}}">{{ctx.text}}</a></li>'
        }
});
```

**Comment by mvcmaker** [comment]
It's a pitty that bootgrid is so discontinued from the creator. Does anybody a working project like bootgrid that has mantainment and woks so fine as bootgrid? I'll think to change to that plugin. Thanks!

**Comment by mvcmaker** [comment]
@RezaErfani67 it doesn't works your code, the generated result is the same, I put on the page loaded event but the result is the same.
```
$(function() { 
............
});
```

**Comment by mvcmaker** [comment]
@canchito-dev I don't know but your code doesn't works for me, only if I put your code inside the main grid object constructor, but I need to place on every grid I create. I place into the loaded event ($(function(){ ............ });)
