### ISSUE TITLE
Is it possible to style only one column? 

### ISSUE THREAD

**Issue by cryan10** [rstaib/jquery-bootgrid#394]
I'd like to format a column with buttons inside so that they are centered in the column. Is this possible, or does styling only apply to entire table?

**Comment by ShiruJan** [comment]
Yes, is possible, with StyleSheet you can modify the vista for specific column

**Comment by ShiruJan** [comment]
example:
<th data-column-id='name' data-css-class='student_name'>Name</th>
<td data-column-id='name' **data-header-css-class='student_name'**>Name</td>

**Comment by ShiruJan** [comment]
Use **data-css-class** and **data-header-css-class** in each column :)
