### ISSUE TITLE
pagination issue for ajax based tables

### ISSUE THREAD

**Issue by musen** [rstaib/jquery-bootgrid#48]
The current post variable is not the same for next/prev links and the page number links. Clicking page 2 results in sending current variable as 2 (which is ok) but when clicking next link while on page 1 results in sending 11. This makes server-side processing impossible since we have 2 different values 2 and 11. Can you please fix this.

**Comment by rstaib** [comment]
If you want to use it that way, you could use the `responseHandler` to parse it to what the component understand or in other words to fulfill the contract between your application and **jQuery Bootgrid**. But in my opinion it is kind a dirty. Sorry for the latency between your request and my answer - I'm a bit busy at the moment.

**Comment by mahmoud-eskandari** [comment]
i try v1.3.1 to use server-side ,But this Issue not Fixed!!! :(
For Example We have <1|2|3|4>
On Ajax
When We click on page 2 Directly bootgrid sending 
{
current:2,
...
}
But When page 1 is active And We click on > (Next Button) it send 
{
current:11
.
.
.
}
to Server And ,
'1'+'1' = 11 
!= 2
maybe This bug happend.
it's very very bad ;~\

**Comment by biglidio** [comment]
**At the library jquery.bootgrid.js, you need to change two few lines:**
_prev: that.current - 1,
next: that.current + 1,_

**change it to:**
_prev: parseInt(that.current) - 1,
next: parseInt(that.current) + 1,_

**Comment by rutpte** [comment]
biglidio that it work.
