### ISSUE TITLE
POST should not be used when querying the server

### ISSUE THREAD

**Issue by nedosa** [rstaib/jquery-bootgrid#51]
I think the decision to use POST to submit page and search parameters to the server is not only incompatible with REST (see here for a discussion http://restcookbook.com/HTTP%20Methods/put-vs-post/), it also makes it awkward to design a decent REST service and worst of all it breaks caching.

I would like for example my bootgrid to query my service at /stuff/ and when I want to add to stuff I can just POST to /stuff/. Right now, even though this is feasible, I need to differentiate based on the POST body, which is far from ideal.

Is there a chance to revert the decision and use GET at all times when bootgrid reads data ?

**Comment by rstaib** [comment]
Fixed in version 1.2.0 which will be publicly available within the next few days.

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.

**Comment by christoff-botes** [comment]
Hi.   I have version 1.2.0 installed but my AJAX requests are still submitting as POST even if I specify GET.  The request ends with HTTP error code 405.  See attached screenshot of F12 in IE and my code below.

< -----script>
     $("#tbGroups1").bootgrid({
         caseSensitive: false,
         ajax: true,
         ajaxSettings: { method: "GET" },
         url: "../api/groups"
        // post: function () {
             /* To accumulate custom parameter with the request object */
        //     return {
        //         id: "b0df282a-0d67-40e5-8558-c9e93b7befed"
        //     };
      //   }         
     })
 <----/script>


![image](https://cloud.githubusercontent.com/assets/12224306/7446538/ea23f03e-f1db-11e4-9f97-1551ed3cd302.png)

**Comment by rstaib** [comment]
I have tested it right now and it works perfect. Propably you still use an old version of bootgrid (perhaps it is cached by your browser).
