### ISSUE TITLE
Default page size of all shows -1 in dropdown vs All

### ISSUE THREAD

**Issue by arndta** [rstaib/jquery-bootgrid#58]
if i set my options as such:
rowCount: [-1, 25, 50, 75]

The currently selected page size will show as "-1", as opposed to "All".

**Comment by rstaib** [comment]
Is fixed in version 1.2.0 which will be publicly available within the next few days.

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.
