### ISSUE TITLE
Hidden columns still listed in the selection list

### ISSUE THREAD

**Issue by K232** [rstaib/jquery-bootgrid#62]
Hi all,
not sure whether this is the expected behavior, but when I hide a column (using data-visible=false on the column) it is still selectable in the dropdown at the upper right and so the user could still display it.
 
Is it possible to remove these columns also from the dropdown list? I still need the columns in the table for some calculations, but there should not be any option for the user to display the column.

Thanks a lot!

**Comment by saivinoth** [comment]
Hey guys any idea about this issue.. I too had this problem

**Comment by rstaib** [comment]
The new attribute is called `data-visible-in-selection` and must be placed on a column. The default value for this attribute is `true`. To exclude a column from the selection box simply set it to `false`.

*Hint: To completly hide a column from the table and the column selection box use: `data-visible="false" data-visible-in-selection="false"`*

**Comment by CharlieHeaps** [comment]
Thanks for this - just what I needed!

**Comment by ShaydullinR** [comment]
@rstaib could u also fix column settings documentation on http://www.jquery-bootgrid.com/Documentation, pls update setting to the correct spelling 'visible-in-selection' instead of 'visibleInSelection'. Thx in advance.
