### ISSUE TITLE
Pagination changes hash

### ISSUE THREAD

**Issue by mikalai-sauchanka** [rstaib/jquery-bootgrid#69]
Currently clicking on pagination's pages changes url's hash which is not always desirable (i.e. in SPAs). I guess it's reasonable to add an option to prevent such behaviour.

**Comment by glennschmidt** [comment]
Can I add a +1 for this feature? The current behaviour makes Bootgrid unsuitable for use with JS applications that use hash-based URL routing.

**Comment by vkbansal** [comment]
I too am looking for this. 

It is difficult to manually override it as `e.stopPropagation()` is used on [Line 488 in dist/jquery.bootgrid.js](https://github.com/rstaib/jquery-bootgrid/blob/cd3e1b3edbc064ab50227390c7ef673887cac193/dist/jquery.bootgrid.js#L488)

**Comment by qzminski** [comment]
I would like to request this feature, too. There is also a nasty bug if you use ```<base>``` tag on your page - when clicking the pagination link, it always performs a redirect.

```html
<head>
<base href="http://www.jquery-bootgrid.com/">
</haed>
```

**Comment by tompazourek** [comment]
+1

Also it changes the hash even when clicking disabled pagination buttons.

**Comment by SaulBurgos** [comment]
I add some changes in the jquery.bootgrid.js to make this work without the hash:

https://gist.github.com/SaulBurgos/edf9dd2de2d4e444c6e5

I here is an example working: http://expirebox.com/download/680b91e1fda466b1558213539ccee33f.html


I needed use this in angularjs.
