### ISSUE TITLE
Using bootgrid for the first time

### ISSUE THREAD

**Issue by LizJohn** [rstaib/jquery-bootgrid#71]
I get the error bootgrid undefined. Not able to figure out the issue. Please help. Attached is my code.

<!DOCTYPE html>
<html>
<head>
    <title>Demo</title>
    <meta charset="utf-8">
    
    

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Scripts/jquery.bootgrid.css" rel="stylesheet" />
</head>
<body>
   
    <table id="grid" class="table table-condensed table-hover table-striped" data-ng>
        <thead>
            <tr>
                <th data-column-id="id">ID</th>
                <th data-column-id="name">Sender</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
    

    <script src="~/Scripts/jquery-1.11.2.js"></script>
    <script src="~/Scripts/jquery-1.11.2.min.js"></script>

    <script src="~/Scripts/jquery.bootgrid.js"></script>

    <script type="text/javascript">
    $(function () {
        $("#grid").bootgrid({
            url: "/api/data/basic"
        });
    });
    </script>

</body>
</html>

**Comment by rstaib** [comment]
Have you tried to enable the `ajax` flag!?

```
    $("#grid").bootgrid({
        ajax: true,
        url: "/api/data/basic"
    });
```

And you should add only one version of *jQuery* (the minified or original, uncompressed version).

**Comment by LizJohn** [comment]
Thank you for the help. I had multiple version of JQuery. It started working once I removed the other.
