### ISSUE TITLE
Custom rows according value

### ISSUE THREAD

**Issue by amandiobm** [rstaib/jquery-bootgrid#72]
How can I customize the rows according to some value in my JSON response.

I have an attribute in my objects that tells me which object are enabled or disabled.

With this value in hand I want to change the entire row color.

What is the better way to do that?

My regards Amandio Magalhães.

And happy new year.

**Comment by rstaib** [comment]
I need a more detailed example. Could you please describe it a bit more!

**Comment by maid450** [comment]
I think my scenario is similar to OP and I also want to know how can I achieve this.

In my JSON response I have a "status" attribute in every row object, and it's not mapped to a column, instead I want to set the tr class accordingly for each table row.

For example, if one row JSON is like this:
{
id: 1,
name: 'John',
status: 'active'
}

it's corresponding tr in the table must have the slass "success" to display in green, however if status was "inactive" the class should be "danger"

**Comment by shadeven** [comment]
@maid450, I am having the same issue like you. Have you got the answer yet?

**Comment by maid450** [comment]
@shadeven no response, I finally made a workaround by setting in a cell the status as data-status="..." then traversing with jQuery all <tr> elements, insepcting the cell status and setting each tr class accordingly.
It works well, but it would be a nice feature to add though

**Comment by shadeven** [comment]
@maid450, Great! I guess @rstaib is too busy to make the enhancement yet.
I roughly understand your solution. Could you please send me some code snippet or jsfiddle would be even better! Thanks in advance.

**Comment by rstaib** [comment]
Contextual classes to color rows is part of version 1.2.0 which will be publicly available within the next few days.

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.

**Comment by maid450** [comment]
How does the feature work exactly?
Do you need to have a "status" property on every "item" object of the response?

**Comment by rstaib** [comment]
Oh yes, you can find a test sample [here](https://github.com/rstaib/jquery-bootgrid/tree/fixes-and-features/demo). You need to have the `status` property in your response object (see the following example). 

```
{
    /*other properties are hidden for simplicity*/
    rows: [
        { id: "item-1", name: "Robert Smith", status: 1 }
    ]
}
```

If you need to change the type of the `status` property just modify the `statusMapping` dictionary (see the following example).

```
$("#grid").bootgrid({
    statusMapping: {
        "suc": "success",
        "inf": "info",
        "war": "warning",
        "dan": "danger"
    }
});
```

**Comment by anaacora** [comment]
Hi rstaib
Thank you for your effort!
I've tried to implement your example, but it confused me alot. Can you provide a complete example for this feature?

Thank you very much in advance!

**Comment by rstaib** [comment]
This example should work with a web api.

HTML:
```html
<table id="grid-data" class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th data-column-id="id" data-type="numeric">ID</th>
            <th data-column-id="sender">Sender</th>
            <th data-column-id="received" data-order="desc">Received</th>
        </tr>
    </thead>
</table>
```

JavaScript:
```javascript
$(function()
{
    $("#grid-data").bootgrid({
        url: "/your/service/url"
    });
});
```

Your response object should look like this:
```javascript
{
  "current": 1,
  "rowCount": 10,
  "rows": [
    {
      "id": 19,
      "sender": "123@test.de",
      "received": "2014-05-30T22:15:00",
      "status": 0
    },
    {
      "id": 14,
      "sender": "123@test.de",
      "received": "2014-05-30T20:15:00",
      "status": 1
    },
    {
      "id": 13,
      "sender": "123@test.de",
      "received": "2014-05-30T20:15:00",
      "status": -1
    },
    ...
  ],
  "total": 1123
}
```

**Comment by anaacora** [comment]
Thank you very much.
It's working now! :smiley:

**Comment by ycklsr** [comment]
Hello,
I don't clearly understand why this feature has been enabled by default, and more importantly why it is based on an object property name as common as "status" is, hence generating some "collisions" issues... Yes, It took me quite a bunch of time to debug the code and see why my rows suddenly looked like a giant rainbow : o ) Anyway, thank you very much for this great plugin.

**Comment by bweber** [comment]
The official documentation for this is wrong. The documentation has `statusMappings` when it should be `statusMapping`.
