### ISSUE TITLE
any example of server-side? 

### ISSUE THREAD

**Issue by yeahe83** [rstaib/jquery-bootgrid#73]
Hi, the question about "rows".

"rows": [
    {
      "id": 19,
      "sender": "123@test.de",
      "received": "2014-05-30T22:15:00"
    },
    {
      "id": 14,
      "sender": "123@test.de",
      "received": "2014-05-30T20:15:00"
    },
    ...
  ],

need i change "rows" value every time according to the current pageindex by myself?

or just need set "rows" to the whole data once, automatic paging data ( like jquery.dataTables )?  

----------------
i cannot find ajax demo in path /demo

**Comment by rstaib** [comment]
If you want to use the `in-memory` technique, you can append the complete rows at once by using the `append` method.

```
var grid = $("#grid").bootgrid();
grid.bootgrid("append", [
     {
          "id": 19,
          "sender": "123@test.de",
          "received": "2014-05-30T22:15:00"
     },
     {
          "id": 14,
          "sender": "123@test.de",
          "received": "2014-05-30T20:15:00"
     },
     ...
]);
```

Or you can use the `server-side` way, where you just return the data  the grid requested.

```
var grid = $("#grid").bootgrid({
    ajax: true,
    url: "your/service/url"
});
```
