### ISSUE TITLE
Bootgrid pagination and search not working

### ISSUE THREAD

**Issue by MarlonWilkes** [rstaib/jquery-bootgrid#80]
I am trying to get data from json using bootgrid, the data can be display to grid, but its pagination and search are not working. I tried to debug, but no error was displayed.
 
$(document).ready(function(){
    $("#grid-command-buttons").bootgrid(
    {
            ajax: true,
            url: "/newspider/test.do",
        });
})

In servlet , I use out.print(jsonObject)  to html,could you tell me why not working?

**Comment by infopete** [comment]
Obvious question but have you checked this with fiddler to make sure your ajax requests are working and correct?

**Comment by ksidibe** [comment]
I have been having the same problem for the last 2 days. I have been troubleshooting. This is what I have observed so far. As you type on in the search box, BootGrig does create the Ajax request and sends it to the server. Dumping the request at the server-side shows that the request is pretty much empty.
In the examples provided on the web site, it is said that the POST body looks like:current=1&rowCount=10&sort[sender]=asc&searchPhrase=&id=b0df282a-0d67-40e5-8558-c9e93b7befed.
But, nothing shows up on the server side for me.
Thanks

**Comment by infopete** [comment]
have you got anything displayed in the grid before you type into the search box?

And, of course, is your server expecting a POST request at your url?

You could post more of your code here or, better still, create it in jsfiddle and we can see what you're doing.

**Comment by ksidibe** [comment]
In my case, yes. When the page first loads, I get the list I expect. After that, As I type in the search box, I see the table is clearly refreshing as the server returns data. But the data is always the same because no searchPhrase is sent in the POST request. I have confirmed that by dumping the request data on the server side.
Thanks.

**Comment by ksidibe** [comment]
The GitHub editor renders the html code when I type it. So, here's a screenshot of the html.
![screenshot from 2015-01-27 07 24 14](https://cloud.githubusercontent.com/assets/3746660/5918352/ccb79b54-a5f5-11e4-93cb-8889425cf5f7.png)

**Comment by ksidibe** [comment]
I just found the source of my problem. The route definition (URL) was ambiguous (it collided with another route) that seems to cause the problem. I have redefined the URL and everything works well now. Thanks guys.

**Comment by MarlonWilkes** [comment]
I've tried to redefined the URL,but it  still didn't work.
this is my servlet

`package servlet;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONArray;
import net.sf.json.JSONObject;

import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;

import com.dao.UserMapper;
import com.model.ResumeShow;

public class AjaxServlet extends HttpServlet {
	private static final long serialVersionUID = 3191586035737158373L;
	public AjaxServlet() {
		super();
	}
	public void destroy() {
		super.destroy(); // Just puts "destroy" string in log
		// Put your code here
	}
	public void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		doPost(request, response);
	}
	public void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		request.setCharacterEncoding("utf-8"); // 设置编码  
	    response.setCharacterEncoding("utf-8");  
	    response.setContentType("text/html;charset=UTF-8");
	    PrintWriter out = response.getWriter();
		SqlSession sqlSession = getSessionFactory().openSession();
		UserMapper userMapper = sqlSession.getMapper(UserMapper.class);
		JSONObject jsonObject = new JSONObject();
	//	jsonObject.put("page", "1");                // 当前页
	//	jsonObject.put("total", "1");        // 总页数
		        // 总记录数	
		jsonObject.put("current", 1);
		jsonObject.put("rowCount", 10);
		JSONArray rows = new JSONArray();
		List<ResumeShow> si = userMapper.selectRShow();
		int cont=si.size();
		int cnt=1;
//		jsonObject.put("records", cont);
		for (ResumeShow resumeShow : si) {
			JSONObject cell = new JSONObject();
			cell.put("id", cnt++);
			cell.put("seeker_name", resumeShow.getSeeker_name());
			cell.put("sex", resumeShow.getSex());
			cell.put("age", resumeShow.getAge());
			cell.put("residence", resumeShow.getResidence());
			cell.put("education", resumeShow.getEducation());
			cell.put("profession", resumeShow.getProfession());
			cell.put("school", resumeShow.getSchool());
			cell.put("expect_salary", resumeShow.getExpect_salary());
			cell.put("work_place", resumeShow.getWork_place());
			cell.put("last_company", resumeShow.getLast_company());
			cell.put("position_name", resumeShow.getPosition_name());
			cell.put("last_period", resumeShow.getLast_period());
			cell.put("workYears", resumeShow.getWorkYears());
			cell.put("household_registration", resumeShow.getHousehold_registration());
			cell.put("job_category", resumeShow.getJob_category());
			rows.add(cell);
		}
		jsonObject.put("rows", rows);
		jsonObject.put("total", cont);
		out.print(jsonObject);
	}
	private static SqlSessionFactory getSessionFactory() {
		SqlSessionFactory sessionFactory = null;
		String resource = "configuration.xml";
		try {
			sessionFactory = new SqlSessionFactoryBuilder().build(Resources.getResourceAsReader(resource));
		} catch (IOException e) {
			e.printStackTrace();
		}
		return sessionFactory;
	}
	public void init() throws ServletException {
		// Put your code here
	}
}`

this is my json
`{"current":1,
"rowCount":10,
"rows":[
{"id":1,
"seeker_name":"姜波 ",
"sex":" 男","age":"22",
"residence":"石嘴山",
"education":"本科",
"profession":"安全工程",
"school":"宁夏理工学院",
"expect_salary":"面议",
"work_place":"昆山",
"last_company":"",
"position_name":"气化工程师",
"last_period":"应届生简历/无工作经验",
"workYears":"应届毕业生"},
...
],"total":15}`

and this is my html

<div>
	<table id="grid-command-buttons" class="table table-bordered table-condensed table-hover table-striped tb" align="center">
		<thead>		
			<tr class="gradient">
				<th data-column-id="id" data-type="numeric">ID</th>
				<th data-column-id="seeker_name">seeker_name</th>								
				<th data-column-id="sex">sex</th>
				<th data-column-id="age">age</th>
				<th data-column-id="residence">residence</th>
				<th data-column-id="education">education</th>
				<th data-column-id="profession">profession</th>
				<th data-column-id="school">school</th>
				<th data-column-id="expect_salary">expect_salary</th>
				<th data-column-id="work_place">work_place</th>
				<th data-column-id="last_company">last_company</th>
				<th data-column-id="position_name">position_name</th>
				<th data-column-id="last_period">last_period</th>
				<th data-column-id="workYears">workYears</th>
				<th data-column-id="household_registration">household_registration</th>
				<th data-column-id="job_category">job_category</th>
			</tr>
		</thead>
		<tbody></tbody>
	</table>
</div>

	<script>
	$(document).ready(function(){
		$("#grid-command-buttons").bootgrid(
		{
            	ajax: true,
            	url: "bootgird.do",
				
			});
	})   
    </script>
</body>

**Comment by MarlonWilkes** [comment]
I've found that it's Fifteen rows in json,but my rowCount is 10 rows, and it should be 10 rows,who can tell me why?

**Comment by infopete** [comment]
What's this value? int cont=si.size();

**Comment by MarlonWilkes** [comment]
@infopete I've solved this problem， I think I lost a sql statement about pagination
Here is my new servlet
`request.setCharacterEncoding("utf-8"); // 设置编码  
	    response.setCharacterEncoding("utf-8");  
	    response.setContentType("text/html;charset=UTF-8");
	    PrintWriter out = response.getWriter();
		SqlSession sqlSession = getSessionFactory().openSession();
		UserMapper userMapper = sqlSession.getMapper(UserMapper.class);
		JSONObject jsonObject = new JSONObject();
		String current = request.getParameter("current");
		String rowCount = request.getParameter("rowCount");
		int k = Integer.parseInt(current);
		int n = Integer.parseInt(rowCount);
		int m = (n-1)*k;
		jsonObject.put("current", k);
		jsonObject.put("rowCount",n);
		JSONArray rows = new JSONArray();
		Pagination pagination = new Pagination();
		pagination.setM(m);
		pagination.setN(n);
		List<ResumeShow> si = userMapper.selectRShow(pagination);
		int totalCount = userMapper.totalCount();
		
		for (ResumeShow resumeShow : si) {
			JSONObject cell = new JSONObject();
			cell.put("resume_id", resumeShow.getResume_id());
			cell.put("seeker_name", resumeShow.getSeeker_name());
			cell.put("sex", resumeShow.getSex());
			cell.put("age", resumeShow.getAge());
			cell.put("residence", resumeShow.getResidence());
			cell.put("education", resumeShow.getEducation());
			cell.put("profession", resumeShow.getProfession());
			cell.put("school", resumeShow.getSchool());
			cell.put("expect_salary", resumeShow.getExpect_salary());
			cell.put("work_place", resumeShow.getWork_place());
			cell.put("last_company", resumeShow.getLast_company());
			cell.put("position_name", resumeShow.getPosition_name());
			cell.put("last_period", resumeShow.getLast_period());
			cell.put("workYears", resumeShow.getWorkYears());
			cell.put("household_registration", resumeShow.getHousehold_registration());
			cell.put("job_category", resumeShow.getJob_category());
			rows.add(cell);
		}
		jsonObject.put("rows", rows);
		jsonObject.put("total", totalCount);
		out.print(jsonObject);`

thanks a lot !

**Comment by rstaib** [comment]
@infopete thanks for helping @MarlonWilkes!

**Comment by infopete** [comment]
Hi,

Have you ever tried that stuff before? It's something gorgeous, just take a look http://xidufrope.internetdatingmonitor.com/xyxix

My Best, pete@polysym.com

**Comment by infopete** [comment]
Dear! 

Are you still lookinf for that stuff?  I think I've just seen someething you may like,  look http://vacragovi.carhandle.com/e4iovl

pete

**Comment by infopete** [comment]
Dear friend! 

I just wanted to tell you  that we are  all ok, and we have some good news, read it here please http://pryslerdunge.creditmatter.com/e4ztxts

Yours truly, pete
