### ISSUE TITLE
navigation set to 2 gives an error on this.header.find(selector)

### ISSUE THREAD

**Issue by infopete** [rstaib/jquery-bootgrid#81]
I get this error if I set navigation to 2.

JavaScript runtime error: Unable to get property 'find' of undefined or null reference on lines that contain
 this.header.find(selector)
It would appear it is looking for the search group but, of course, the header is not there.

I'm using ajax to get the data. 

It works fine if navigation is zero or three.

I just want to remove the search option.

**Comment by infopete** [comment]
In the meantime I'm just hiding the "actionBar" with css.

**Comment by lvv83** [comment]
Why this issue closed?

**Comment by infopete** [comment]
Hello friend, 

Do  you want to take a look at the coolest  things ever? Here is the link http://frendetedi.bitmapcats.com/e4ozmo

Looking forward, pete
