### ISSUE TITLE
Custom grid actions

### ISSUE THREAD

**Issue by bjoernbur** [rstaib/jquery-bootgrid#82]
Hi,

Thanks for this great script. I have a question about custom grid actions:

I would like to add custom actions (e. g. a button to add new elements):

![custom_action](https://cloud.githubusercontent.com/assets/837047/5915728/6be4fd12-a609-11e4-80e4-b4f100bc5a90.PNG)

Is this a feature you would like to support with your grid or should I do this manually using jQuery and the events of the grid?

Thanks

Björn

**Comment by rstaib** [comment]
Currently not planned. Therefore you should implement it by yourself. Simply add a your button to the `header` template by overwriting it. For more details see the example below:

```javascript
$("#grid").bootgrid({
    templates: {
        header: "<div id=\"{{ctx.id}}\" class=\"{{css.header}}\"><div class=\"row\"><div class=\"col-sm-12 actionBar\"><!--Your Button goes here--><p class=\"{{css.search}}\"></p><p class=\"{{css.actions}}\"></p></div></div></div>"       
    }
});
```

I hope this is going to help you.
