### ISSUE TITLE
need method to clear search and sort selection

### ISSUE THREAD

**Issue by jhargis** [rstaib/jquery-bootgrid#89]
After a sort or search option is selected there is no method for resetting / clearing them.

**Comment by rstaib** [comment]
Implemented in version 1.2.0 which will be publicly awailable within the next few days.

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.
