### ISSUE TITLE
How can i obtain cell value on click? 

### ISSUE THREAD

**Issue by mdemori** [rstaib/jquery-bootgrid#91]
Hi, 

I've make a simple test with below code 

var grid = $("#grid-data").bootgrid({
... .... 
}).on("click.rs.jquery.bootgrid", function(e, rows){
				console.log(rows);
			}

When i click on a row,  i will find all row columns in "Rows" but seem that this columns are only headers with field id and header description.
There is way to get the value of specific column on click?

**Comment by rstaib** [comment]
As described [here](http://www.jquery-bootgrid.com/Documentation#events) you need to add three parameters. See the fixed code snippet below!

```javascript
var grid = $("#grid-data").bootgrid({
...
}).on("click.rs.jquery.bootgrid", function(e, columns, rows)
{
    /*
    e         jQuery EventArgs
    columns   An array of columns.
    rows      An array of rows.
    */
}
```

Sorry for the late answer but I'm quite busy.

**Comment by rstaib** [comment]
> There is way to get the value of specific column on click? 

To get an idea of how you get the value of a specific cell see the [command buttons](http://www.jquery-bootgrid.com/Examples#command-buttons) example.

**Comment by ashokramkumar** [comment]
I found out a solution for individual columns
<table class="table" id="main-grid" data-getter="/cccccc.cfm?action=getter">
	<thead>
		<tr>
			<th data-column-id="CustomerID" data-formatter="CustomerID" data-css-class="pointer-hand">Customer ID</th>
			<th data-column-id="Name" data-formatter="Name" data-css-class="**stop-click-event**">Name</th>
</tr></thead></table>
<script>
var bootgrid = $("#grid1").bootgrid(config);

bootgrid.on("click.rs.jquery.bootgrid", function (e, columns, row, target) {
    console.log('Incident Id: ' + row.IncidentId);
});

bootgrid.on("loaded.rs.jquery.bootgrid", function (e, c, rows) {
    // avoid any element with "stop-click-event" class from triggering the event in the grid...
    $(".stop-click-event").click(function(e) {
        e.preventDefault();
        e.stopPropagation();
    });
});
</script>
