### ISSUE TITLE
Drop-down list

### ISSUE THREAD

**Issue by shadeven** [rstaib/jquery-bootgrid#95]
Does this plugin support a drop-down list in one table cell?

**Comment by jhargis** [comment]
@shadeven you can put any content in a cell you want using the formatters.

http://www.jquery-bootgrid.com/Documentation#formatters

**Comment by shadeven** [comment]
Thanks, @jhargis. I will give it a go.

**Comment by chrisplusplus** [comment]
The problem here is the action on select - It's very difficult to capture the list item that is selected and apply and event on click.  I haven't been able to figure this out

**Comment by rstaib** [comment]
@chrisplusplus The events must be applied after rendering or in other words use the `loaded` event.

**Comment by rstaib** [comment]
@chrisplusplus See the example [here](http://www.jquery-bootgrid.com/Examples#command-buttons).

**Comment by chrisplusplus** [comment]
I don't know how I missed this.  Thank you so much that worked perfectly.

Chris Williams
Senior Web Developer
Clearwater, FL
731-445-4904
