### ISSUE TITLE
Pagination option for when you have a lot of pages

### ISSUE THREAD

**Issue by bgarrison25** [rstaib/jquery-bootgrid#98]
Currently I have some uses for bootgrid where I have over 400 pages of information. It works great except that pagination shows every single page instead of having some form of concatenation. Instead of 1 2 3 ..... 50 it shows every single page. Here is a screenshot of what I am talking about.

![untitled](https://cloud.githubusercontent.com/assets/2955550/6116685/bb529a3a-b07c-11e4-8d3a-6f82a928131b.png)

**Comment by rstaib** [comment]
Could you please send me your config or even better create an jsfiddle!?

**Comment by bgarrison25** [comment]
even better....here is the app im working on....i made it public so you could view it:

http://wgarrisondev.mainstreethost.com/mage-product-redirects/public/

**Comment by bgarrison25** [comment]
also ...my config is like this

```
var grid = $("#grid-basic").bootgrid({
                padding: 50,
                headerAlign: 'center',
                formatters: {
                    "commands": function (column, row)
                    {
                        return "<button type=\"button\" class=\"btn btn-xs btn-default command-edit\" data-row-id=\"" + row.id + "\"><span class=\"glyphicon glyphicon-pencil\"></span></button> " +
                                "<button type=\"button\" class=\"btn btn-xs btn-default command-delete\" data-row-id=\"" + row.id + "\"><span class=\"glyphicon glyphicon-trash\"></span></button>";
                    }
                }
            }).on("loaded.rs.jquery.bootgrid", function () {
                /* Executes after data is loaded and rendered */
                grid.find(".command-edit").on("click", function (e) {
                    alert("You pressed edit on row: " + $(this).data("row-id"));
                }).end().find(".command-delete").on("click", function (e) {
                    alert("You pressed delete on row: " + $(this).data("row-id"));
                });
                $('#grid-container').removeClass('hidden');
            });
```

**Comment by bgarrison25** [comment]
i dont use the grid's ajax option (although i probably could). I build a table with all the entries and then run the plugin against it. Could this be why?

**Comment by rstaib** [comment]
No, the `ajax` option isn't the reason why it isn't working. But rather this `padding: 50` option. In worst case you will get 101 buttons for specific pages when using `50` for `padding`.
